src/shapes/draw.ts, src/useGraph/schematics/edge.ts, src/useGraph/useGraph.ts
=> fix bi-directional edge bug

src/Graph.vue, src/useGraph/useDraggableGraph.ts, src/useGraph/useGraphBase.ts, src/useGraph/useNodeAnchorGraph.ts, src/useGraph/usePersistentGraph.ts, src/useGraph/useUserEditableGraph.ts
debugging the new options system and added a toolbar to graph
=> New Options API Verified

src/useGraph/schematics/edge.ts
make sure I did the edge schema properly
=> Stop edge overlap with node

package-lock.json, package.json, src/App.vue, src/Graph.vue, src/markov-chains/colors.ts, src/markov-chains/helpers.ts, src/markov-chains/sccColorizer.ts, src/markov-chains/tarjansSCC.ts, src/markov-chains/useSCC.ts, src/useGraph/tutorial/index.ts, src/useGraph/tutorial/sequences/basics.ts, src/useGraph/tutorial/sequences/sequences.ts, src/useGraph/tutorial/types.ts, src/useGraph/tutorial/useGraphTutorial.ts, src/useGraph/tutorial/useTutorial.ts, src/useGraph/useBaseGraph.ts, src/useGraphBtns.ts
added the start of the markov chain implementation
added the brand new "useGraphTutorial" API for interactive user tutorials and lessons
=> Markov coloring and tutorial API

package-lock.json, package.json, src/Graph.vue, src/graphColorizers.ts, src/graphConverters.test.ts, src/useGraph/helpers.ts, src/useGraph/schematics/edge.ts, src/useGraph/schematics/node.ts, src/useGraph/theme/index.ts, src/useGraph/theme/types.ts, src/useGraph/theme/useTheme.ts, src/useGraph/themes.ts, src/useGraph/tutorial/sequences/basics.ts, src/useGraph/tutorial/types.ts, src/useGraph/types.ts, src/useGraph/useBaseGraph.ts, src/useGraph/useNodeAnchorGraph.ts
brand new useTheme api provides a hook to effortlessly add, remove, layer, and track themes from multiple sources.
=> useTheme API

src/ShapePlayground.vue, src/shapes/uturn/draw.ts, src/shapes/uturn/hitbox.ts, src/shapes/uturn/text.ts
New Version of last PR (#66) to match with newest `magic-shapes` API
=> Fix uturnarrow bug

client/src/App.vue, client/src/graphs/compositions/useFocusGraph.ts, client/src/graphs/schematics/node.ts, client/src/playground/shape/ShapePlayground.vue, client/src/shapes/circle/draw.ts, client/src/shapes/circle/index.ts, client/src/shapes/circle/text.ts, client/src/shapes/rect/draw.ts, client/src/shapes/rect/index.ts, client/src/shapes/rect/text.ts, client/src/shapes/square/index.ts, client/src/shapes/square/text.ts, client/src/shapes/text.ts
added text area to circles, rects, squares
=> Update text to text area

client/src/graphs/buttons/useGraphBtns.ts, client/src/graphs/compositions/useBaseGraph/index.ts, client/src/graphs/compositions/useBaseGraph/tests/addEdge.test.ts, client/src/graphs/compositions/useBaseGraph/types.ts, client/src/graphs/compositions/useCollaborativeGraph/index.ts, client/src/graphs/compositions/useCollaborativeGraph/types.ts, client/src/graphs/compositions/useDraggableGraph/index.ts, client/src/graphs/compositions/useFocusGraph/index.ts, client/src/graphs/compositions/useMarqueeGraph/index.ts, client/src/graphs/compositions/useNodeAnchorGraph/index.ts, client/src/graphs/compositions/usePersistentGraph/index.ts, client/src/graphs/compositions/useUserEditableGraph/index.ts, client/src/graphs/events/index.ts, client/src/graphs/events/types.ts, client/src/graphs/schematics/edge.ts, client/src/graphs/settings/index.ts, client/src/graphs/themes/index.ts, client/src/graphs/themes/types.ts, client/src/graphs/tutorials/sequences/basics.ts, client/src/graphs/types.ts, client/src/playground/graph/GraphPlayground.vue, server/dist/clientTypes.js, server/dist/sockets.js, server/src/clientTypes.ts, server/src/sockets.ts
* Marquee
* Focusable
* FocusBlacklist
=> Edge Label replaces edge weight and 3 new settings!

README.md
=> docs(setup): make more friendly

package.json
colorizes the terminal output:
| before | after_ |
|--------|--------|
| <img width="534" alt="image" src="https://github.com/user-attachments/assets/4248f771-98fb-42b6-8f96-d0208591014e"> | <img width="534" alt="image" src="https://github.com/user-attachments/assets/a1249606-18b5-41e1-b7f4-202f2d4d3a29"> |
=> feat(concurrently): colorize dev output

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/line/hitbox.ts, client/src/shapes/rect/hitbox.ts, client/src/shapes/square/hitbox.ts, client/src/shapes/triangle/draw.ts, client/src/shapes/triangle/hitbox.ts, client/src/shapes/triangle/index.ts, client/src/shapes/triangle/text.ts
also fixed stroke hitbox on rect/square
=> Add stroke and label to triangle

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/circle/text.ts, client/src/shapes/text.ts
=> implement text vertical offset

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/rect/text.ts, client/src/shapes/text.ts
=> Add text box width

client/src/graphs/compositions/useFocusGraph/index.ts, client/src/playground/shape/Toolbar.vue, client/src/shapes/arrow/index.ts, client/src/shapes/circle/index.ts, client/src/shapes/line/index.ts, client/src/shapes/rect/index.ts, client/src/shapes/square/index.ts, client/src/shapes/text.ts, client/src/shapes/textarea.ts, client/src/shapes/types.ts, client/src/shapes/uturn/index.ts
Also improved:
- how text input appears during text input
- text input behaves after enter keypress or click outside
=> fix(textArea): Update text area to scale with canvas zoom in/out

client/src/graphs/useTransitionMatrix.ts, client/src/products/graph-sandbox/GraphInfoMenu.vue, client/src/products/graph-sandbox/TransitionMatrixDisplay.vue
no longer has normalized weights
=> fix(graphInfo): fix transition matrix

client/src/products/graph-sandbox/ui/GraphInfoMenu.vue, client/src/products/graph-sandbox/ui/TransitionMatrixDisplay.vue
=> feat(magic-graphs): add tooltips to transition matrix

client/src/shapes/textarea.ts
=> fix(magic-graphs): edge text did not deselect when clicked off

client/src/ui/core/button/Button.vue, client/src/ui/graph/select/GSpreadSelect.vue, client/src/ui/product/sim/SimulationPlaybackControls.vue, client/src/ui/product/sim/types.ts, client/src/ui/product/sim/useSimulationControls.ts
still need to make colors work, will do that next commit. just verify functionality...
=> feat(magic-graphs): add sim playback speed controls

client/src/graphs/plugins/marquee/index.ts
=> fix(magic-graphs): node anchors appear when marquee selecting

client/src/graphs/plugins/annotations/index.ts
=> fix(magic-graphs): move eraser color to graph colors

client/src/graphs/events/index.ts, client/src/graphs/events/types.ts, client/src/graphs/plugins/anchors/index.ts, client/src/graphs/plugins/marquee/index.ts
adds eventbus options for marquee selecting
=> feat(magic-graphs): add marquee selection event bus

client/src/ui/product/sim/SimulationPlaybackControls.vue, client/src/ui/product/sim/useSimulationControls.ts
=> feat(product): add persistent sim speed

client/src/shapes/uturn/draw.ts
=> fix(magic-shapes): uturn thickness bug

client/src/graphs/plugins/marquee/helpers.ts, client/src/graphs/plugins/marquee/index.ts, client/src/graphs/templates/helpers.ts, client/src/graphs/templates/useGraphTemplate.ts
=> feat(magic-graphs): move template to marquee encapsulation box system

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/ellipse/draw.ts, client/src/shapes/ellipse/hitbox.ts, client/src/shapes/ellipse/index.ts, client/src/shapes/ellipse/text.ts, client/src/shapes/index.ts, client/src/shapes/types.ts
=> feat(magic-shapes): add oval shape

client/src/App.vue, client/src/graphs/plugins/shortcut/index.ts, client/src/graphs/settings/index.ts, client/src/main.ts
reminds users it is saved automatically
=> feat(magic-graphs): add save hotkey

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/arrow/draw.ts, client/src/shapes/line/draw.ts, client/src/shapes/line/index.ts, client/src/shapes/triangle/draw.ts, client/src/shapes/triangle/index.ts, client/src/shapes/types.ts
=> feat(magic-shapes): add gradients to triangle, line, and arrow

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/arrow/draw.ts, client/src/shapes/arrow/index.ts
=> feat(magic-shapes): add custom shape as arrowhead

client/src/shapes/uturn/draw.ts, client/src/shapes/uturn/hitbox.ts, client/src/shapes/uturn/index.ts
=> refactor(magic-shapes): move uturn to arrow standard

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/arrow/draw.ts, client/src/shapes/arrow/hitbox.ts, client/src/shapes/arrow/index.ts, client/src/shapes/rect/hitbox.ts, client/src/shapes/square/hitbox.ts, client/src/shapes/square/index.ts, client/src/shapes/uturn/index.ts
also fixed really scary bug with hit boxes not working if border radius property was undefined
=> fix(magic-shapes): add hitboxes to custom arrow heads

client/src/graphs/templates/useGraphTemplate.ts, client/src/graphs/useAnimateColorPulse.ts, client/src/utils/animate.ts
also updated interpolate colors function to take a list of colors
=> feat(product): add pulsing edges animation

client/src/graphs/useAnimateColorPulse.ts
=> feat(product): add pulsing animation to nodes

client/src/playground/shape/ShapePlayground.vue, client/src/shapes/helpers.ts, client/src/shapes/types.ts, client/src/shapes/uturn/draw.ts, client/src/shapes/uturn/index.ts
=> feat(magic-shapes): Add gradient to uturn

client/src/graphs/schematics/edge.ts, client/src/graphs/schematics/edgeUturn.ts, client/src/graphs/schematics/uturnSeq.ts, client/src/shapes/uturn/draw.ts
animates the width.
also fixed bug introduced with gradients in #345
=> feat(magic-shapes): add basic uturn animation

client/src/ui/product/sim/SimulationPlaybackControls.vue
=> feat(product): add simulation playback keyboard controls

client/src/graphs/templates/autoGenerate/AutoGenerateSettingsMenu.vue, client/src/graphs/templates/autoGenerate/generationAlgorithms/randomGeneration.ts, client/src/graphs/templates/autoGenerate/types.ts, client/src/graphs/templates/autoGenerate/useAutoGenerate.ts
=> feat(magic-graphs): add options for bidirectional edges and uturns in autogenerate graph

client/src/shapes/helpers.ts, client/src/shapes/text.ts, client/src/shapes/types.ts
moving towards converting text to full shape
=> feat(magic-shapes): add font family to text

client/src/ui/product/GraphProduct.vue
=> feat(product): prevent abrupt dragging stop when dragging over html elements above canvas

client/src/ui/product/GraphProduct.vue, client/src/ui/product/sim/SelectSim.vue
fixes #362
also cleaned up annotation overlay
fixes #358
=> fix(product): disable sim button while annotation

client/src/graphs/global.ts, client/src/graphs/plugins/annotations/index.ts, client/src/graphs/useGraphProduct.ts, client/src/ui/product/dropdown/ProductItem.vue
=> feat(product): gowithgraph supports annotations

client/src/graphs/plugins/shortcut/index.ts, client/src/ui/core/GDialog.vue, client/src/ui/product/CommandPalette.vue, client/src/ui/product/GraphProduct.vue
=> feat(product): add help menu

client/src/shapes/helpers.ts, client/src/shapes/text.ts, client/src/shapes/useTextDimensionsOnCanvas.ts
canvas is now maintained instead of being created and deleted doubling or tripling performance
=> bug(magic-shapes): fix memory leak with text dimension canvas

client/.prettierrc, client/package-lock.json, client/package.json
=> chore(prettier): update prettier config

client/.prettierrc, client/index.html, client/package-lock.json, client/package.json, client/src/graphs/templates/autoGenerate/AutoGenerate.vue, client/src/main.ts, client/src/products/graph-sandbox/ui/AnnotationToolbar.vue, client/src/products/graph-sandbox/ui/CollaborativeSessionMenu.vue, client/src/products/graph-sandbox/ui/GraphInfoMenu/AdjacencyListDisplay.vue, client/src/products/graph-sandbox/ui/IslandToolbar.vue, client/src/products/graph-sandbox/ui/TreeShapeMenuSettings.vue, client/src/router/404.vue, client/src/ui/core/Icon.vue, client/src/ui/graph/GHoverInfo.vue, client/src/ui/product/CommandPalette.vue, client/src/ui/product/FullscreenButton.vue, client/src/ui/product/ThemeToolbar.vue, client/src/ui/product/ZoomButtons.vue, client/src/ui/product/sim/SelectSim.vue, client/src/ui/product/sim/SimulationPlaybackControls.vue
fixes #361
moved away from google font icons
moved towards standard material design icons
-> renamed all applicable icons and refactored the Icon.vue component to reflect changes
=> refactor(magic-ui): update icons to material design icons

client/src/ui/product/dropdown/ProductItem.vue
fixes todo comments in product menu file
=> refactor(magic-ui): move svg icons over to material icons in product menu

client/src/graphs/plugins/annotations/index.ts, client/src/products/graph-sandbox/ui/AnnotationToolbar.vue, client/src/shapes/scribble/draw.ts, client/src/shapes/scribble/hitbox.ts, client/src/shapes/scribble/index.ts
also improve efficiency of erasing annotations in magic-graph product
=> feat(magic-shapes): add  single coordinate annotations

client/src/graphs/plugins/annotations/index.ts, client/src/products/graph-sandbox/ui/AnnotationToolbar.vue
=> feat(product): add laser pointer to annotations

client/src/shapes/textarea.ts
=> fix(magic-shapes): fix text bug where text box grows on click when zoomed out

client/src/shapes/text.ts, client/src/shapes/textarea.ts, client/src/shapes/useTextDimensionsOnCanvas.ts
I think I actually fixed the bug this time lol
=> refactor(magic-shapes): text input refactor to use textOnCanvas api

client/package.json, client/src/graphs/buttons/GraphBtns.vue, client/src/playground/graph/GraphPlayground.vue, client/src/products/graph-sandbox/Main.vue, client/src/products/graph-sandbox/ui/IslandMarkup.vue, client/src/products/graph-sandbox/ui/MarkupMenu/InputColor.vue, client/src/products/graph-sandbox/ui/MarkupMenu/InputSize.vue, client/src/products/graph-sandbox/ui/TreeShapeMenu.vue, client/src/products/graph-sandbox/ui/TreeShapeMenuSettings.vue, client/src/products/search-visualizer/Main.vue, client/src/products/search-visualizer/components/CodeEditor.vue, client/src/ui/core/Popover.vue
=> chore: fix some linting errors

client/src/ui/product/ZoomButtons.vue, client/src/utils/components/usePinchToZoom.ts
added function to allow scale to change by percent.
fixes comment inside of #386
=> feat: add zoom scale by percent

client/src/ui/product/HelpMenu.vue
=> feat: add shortcut to open help menu

client/package-lock.json, client/src/ui/core/button/VerticalCardButton.vue
=> fix: product thumbnail aspect ratios

client/src/shapes/scribble/hitbox.ts
bounding box didn't take brush weight into account
=> fix: scribble hitbox now accounts for brush weight

client/src/canvas/camera/panZoom.ts, client/src/graphs/base/index.ts, client/src/graphs/plugins/anchors/index.ts, client/src/graphs/plugins/drag/index.ts, client/src/ui/core/toolbar/ToolbarButton.vue, client/src/ui/graph/toolbar/GToolbarBase.vue, client/src/ui/graph/toolbar/GToolbarButton.vue, client/src/ui/product/GraphProduct.vue, client/src/ui/product/dropdown/ProductDropdown.vue, client/src/ui/product/sim/SelectSim.vue
Fixes #458
and some other stuff:
- now you can interact with the canvas in the space between the UI toolbars and the side of the screen
- buttons in the ui are clearly focusable 
- in the main interface: interactive controls are ordered correctly in the DOM for keyboard tabbing
- Magic Algorithms/Select Product and Select Simulation/Play Button turn an active color when interacting with them
- fixed zoom jittery-ness caused by tiny rounding issues on the canvas cameras pan and zoom logic
- focusing the canvas now steals focus from any other DOM element that may be in focus
- removed bits of dead code and simplified anchor + drag logic
=> fix(graph): misc bug fixes and accessibility improvements

client/package-lock.json, client/src/playground/shape/ShapePlayground.vue, client/src/shapes/helpers.ts, client/src/shapes/shapes/cross/draw.ts, client/src/shapes/shapes/cross/hitbox.ts, client/src/shapes/shapes/rect/draw.ts, client/src/shapes/types/schema.ts
cross now has individual border radii
cross no longer overlaps in center (#457)
=> feat(shapes): update cross

client/src/ui/product/help/HelpShortcutKey.vue
=> fix(ui): border color on light mode
